export interface Category {
  id: string;
  name: string;
  image: string;
  lessonCount: number;
}

export interface Lesson {
  id: string;
  category_id: string;
  title: string;
  description: string;
  level: string;
  duration_minutes: number;
  xp_reward: number;
}

export const CATEGORIES: Category[] = [
  {
    id: 'daily',
    name: 'Daily English',
    image: '/images/lessons/daily.jpg',
    lessonCount: 10,
  },
  {
    id: 'interview',
    name: 'Interview English',
    image: '/images/lessons/interview.jpg',
    lessonCount: 10,
  },
  {
    id: 'business',
    name: 'Business English',
    image: '/images/lessons/business.jpg',
    lessonCount: 10,
  },
  {
    id: 'travel',
    name: 'Travel English',
    image: '/images/lessons/travel.jpg',
    lessonCount: 10,
  },
];

const LESSONS_DATABASE: Record<string, Lesson[]> = {
  daily: [
    {
      id: 'daily-1',
      category_id: 'daily',
      title: 'Introduction',
      description: 'Learn simple ways to introduce yourself and break the ice.',
      level: 'Beginner',
      duration_minutes: 5,
      xp_reward: 20,
    },
    {
      id: 'daily-2',
      category_id: 'daily',
      title: 'Ordering at a Cafe',
      description: 'Practice coffee shop dialogues and common ordering phrases.',
      level: 'Beginner',
      duration_minutes: 6,
      xp_reward: 25,
    },
    {
      id: 'daily-3',
      category_id: 'daily',
      title: 'Casual Conversation',
      description: 'Master small talk techniques with friends and acquaintances.',
      level: 'Beginner',
      duration_minutes: 8,
      xp_reward: 30,
    },
    {
      id: 'daily-4',
      category_id: 'daily',
      title: 'Shopping',
      description: 'Ask for prices, sizes, and assistance in retail stores.',
      level: 'Beginner',
      duration_minutes: 7,
      xp_reward: 25,
    },
    {
      id: 'daily-5',
      category_id: 'daily',
      title: 'Asking Directions',
      description: 'Give and understand clear street directions around town.',
      level: 'Intermediate',
      duration_minutes: 7,
      xp_reward: 30,
    },
    {
      id: 'daily-6',
      category_id: 'daily',
      title: 'At a Restaurant',
      description: 'Reserve a table, order meals, and request the check confidently.',
      level: 'Intermediate',
      duration_minutes: 8,
      xp_reward: 35,
    },
    {
      id: 'daily-7',
      category_id: 'daily',
      title: 'Talking About Weekends',
      description: 'Describe past activities and discuss future weekend plans.',
      level: 'Intermediate',
      duration_minutes: 6,
      xp_reward: 30,
    },
    {
      id: 'daily-8',
      category_id: 'daily',
      title: 'At the Doctor',
      description: 'Explain symptoms, medical conditions, and pharmacy needs.',
      level: 'Intermediate',
      duration_minutes: 9,
      xp_reward: 40,
    },
    {
      id: 'daily-9',
      category_id: 'daily',
      title: 'Phone Calls',
      description: 'Handle professional and casual phone conversations smoothly.',
      level: 'Advanced',
      duration_minutes: 10,
      xp_reward: 45,
    },
    {
      id: 'daily-10',
      category_id: 'daily',
      title: 'Sharing Opinions',
      description: 'Express agreement, polite disagreement, and strong viewpoints.',
      level: 'Advanced',
      duration_minutes: 12,
      xp_reward: 50,
    },
  ],
  interview: [
    {
      id: 'interview-1',
      category_id: 'interview',
      title: 'Self Introduction',
      description: 'Craft a compelling pitch to answer "Tell me about yourself".',
      level: 'Beginner',
      duration_minutes: 6,
      xp_reward: 25,
    },
    {
      id: 'interview-2',
      category_id: 'interview',
      title: 'Behavioral Questions',
      description: 'Structure answers using the STAR method (Situation, Task, Action, Result).',
      level: 'Intermediate',
      duration_minutes: 10,
      xp_reward: 40,
    },
    {
      id: 'interview-3',
      category_id: 'interview',
      title: 'Motivation',
      description: 'Articulate why you want this role and company.',
      level: 'Intermediate',
      duration_minutes: 8,
      xp_reward: 35,
    },
    {
      id: 'interview-4',
      category_id: 'interview',
      title: 'Strengths',
      description: 'Highlight your top professional skills with concrete examples.',
      level: 'Intermediate',
      duration_minutes: 7,
      xp_reward: 30,
    },
    {
      id: 'interview-5',
      category_id: 'interview',
      title: 'Weaknesses',
      description: 'Discuss areas for growth honestly and constructively.',
      level: 'Intermediate',
      duration_minutes: 8,
      xp_reward: 35,
    },
    {
      id: 'interview-6',
      category_id: 'interview',
      title: 'Technical Questions',
      description: 'Explain domain expertise clearly to technical and non-technical interviewers.',
      level: 'Advanced',
      duration_minutes: 11,
      xp_reward: 45,
    },
    {
      id: 'interview-7',
      category_id: 'interview',
      title: 'Salary Discussion',
      description: 'Navigate compensation expectations professionally.',
      level: 'Advanced',
      duration_minutes: 9,
      xp_reward: 40,
    },
    {
      id: 'interview-8',
      category_id: 'interview',
      title: 'Asking Questions',
      description: 'Ask insightful questions at the end of the interview.',
      level: 'Intermediate',
      duration_minutes: 7,
      xp_reward: 30,
    },
    {
      id: 'interview-9',
      category_id: 'interview',
      title: 'Difficult Questions',
      description: 'Respond calmly to unexpected or tricky questions.',
      level: 'Advanced',
      duration_minutes: 12,
      xp_reward: 50,
    },
    {
      id: 'interview-10',
      category_id: 'interview',
      title: 'Closing the Interview',
      description: 'Leave a lasting positive impression and follow up effectively.',
      level: 'Intermediate',
      duration_minutes: 6,
      xp_reward: 25,
    },
  ],
  business: [
    {
      id: 'business-1',
      category_id: 'business',
      title: 'Business Meeting',
      description: 'Lead agenda items, state points, and manage meeting flow.',
      level: 'Intermediate',
      duration_minutes: 9,
      xp_reward: 40,
    },
    {
      id: 'business-2',
      category_id: 'business',
      title: 'Professional Email',
      description: 'Write clear, concise, and professional workplace emails.',
      level: 'Beginner',
      duration_minutes: 6,
      xp_reward: 25,
    },
    {
      id: 'business-3',
      category_id: 'business',
      title: 'Negotiation',
      description: 'Propose win-win terms, push back politely, and reach agreements.',
      level: 'Advanced',
      duration_minutes: 12,
      xp_reward: 50,
    },
    {
      id: 'business-4',
      category_id: 'business',
      title: 'Presentation',
      description: 'Deliver persuasive slideshows and field audience Q&A.',
      level: 'Intermediate',
      duration_minutes: 10,
      xp_reward: 45,
    },
    {
      id: 'business-5',
      category_id: 'business',
      title: 'Networking',
      description: 'Build professional relationships at corporate events.',
      level: 'Intermediate',
      duration_minutes: 8,
      xp_reward: 35,
    },
    {
      id: 'business-6',
      category_id: 'business',
      title: 'Difficult Conversations',
      description: 'Give constructive feedback and handle workplace conflicts.',
      level: 'Advanced',
      duration_minutes: 11,
      xp_reward: 45,
    },
    {
      id: 'business-7',
      category_id: 'business',
      title: 'Corporate Etiquette',
      description: 'Understand formal business culture and cross-cultural manners.',
      level: 'Beginner',
      duration_minutes: 7,
      xp_reward: 30,
    },
    {
      id: 'business-8',
      category_id: 'business',
      title: 'Remote Work',
      description: 'Communicate efficiently over video calls and messaging tools.',
      level: 'Beginner',
      duration_minutes: 6,
      xp_reward: 25,
    },
    {
      id: 'business-9',
      category_id: 'business',
      title: 'Sales',
      description: 'Pitch products, handle customer objections, and close deals.',
      level: 'Advanced',
      duration_minutes: 10,
      xp_reward: 40,
    },
    {
      id: 'business-10',
      category_id: 'business',
      title: 'Leadership',
      description: 'Inspire teams, delegate tasks, and communicate vision.',
      level: 'Advanced',
      duration_minutes: 12,
      xp_reward: 50,
    },
  ],
  travel: [
    {
      id: 'travel-1',
      category_id: 'travel',
      title: 'At the Airport',
      description: 'Check in baggage, navigate security, and handle boarding gates.',
      level: 'Beginner',
      duration_minutes: 7,
      xp_reward: 30,
    },
    {
      id: 'travel-2',
      category_id: 'travel',
      title: 'Hotel Check-in',
      description: 'Request room preferences, report issues, and complete check-out.',
      level: 'Beginner',
      duration_minutes: 6,
      xp_reward: 25,
    },
    {
      id: 'travel-3',
      category_id: 'travel',
      title: 'Restaurant',
      description: 'Inquire about local specialties, dietary needs, and payment.',
      level: 'Beginner',
      duration_minutes: 8,
      xp_reward: 30,
    },
    {
      id: 'travel-4',
      category_id: 'travel',
      title: 'Transport',
      description: 'Buy train tickets, ride taxis, and navigate public transit systems.',
      level: 'Beginner',
      duration_minutes: 5,
      xp_reward: 20,
    },
    {
      id: 'travel-5',
      category_id: 'travel',
      title: 'Directions',
      description: 'Ask locals for guidance and locate famous landmarks.',
      level: 'Intermediate',
      duration_minutes: 7,
      xp_reward: 30,
    },
    {
      id: 'travel-6',
      category_id: 'travel',
      title: 'Shopping',
      description: 'Bargain at local markets and buy souvenirs.',
      level: 'Intermediate',
      duration_minutes: 6,
      xp_reward: 25,
    },
    {
      id: 'travel-7',
      category_id: 'travel',
      title: 'Emergencies',
      description: 'Contact emergency services, describe lost items, and seek help.',
      level: 'Intermediate',
      duration_minutes: 9,
      xp_reward: 40,
    },
    {
      id: 'travel-8',
      category_id: 'travel',
      title: 'Local Etiquette',
      description: 'Respect cultural customs and social norms while traveling.',
      level: 'Intermediate',
      duration_minutes: 8,
      xp_reward: 35,
    },
    {
      id: 'travel-9',
      category_id: 'travel',
      title: 'Trip Planning',
      description: 'Book tours, rent vehicles, and arrange sightseeing itineraries.',
      level: 'Advanced',
      duration_minutes: 10,
      xp_reward: 45,
    },
    {
      id: 'travel-10',
      category_id: 'travel',
      title: 'Solving Problems',
      description: 'Handle missed flights, lost luggage, and hotel reservation errors.',
      level: 'Advanced',
      duration_minutes: 11,
      xp_reward: 50,
    },
  ],
};

export async function getCategories(): Promise<Category[]> {
  return CATEGORIES;
}

export async function getCategory(categoryId: string): Promise<Category | null> {
  const found = CATEGORIES.find((c) => c.id === categoryId);
  return found || null;
}

export async function getLessons(categoryId: string): Promise<Lesson[]> {
  return LESSONS_DATABASE[categoryId] || [];
}
